# Generated by Django 2.0 on 2019-06-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='existencia',
            field=models.IntegerField(blank=True, db_column='EXISTENCIA', null=True),
        ),
    ]
